---
# Install proxmox-backup-client automatically?
pbc_install_client: true

# deb822 repo config
pbc_client_suite: bookworm
pbc_keyring_url: "https://enterprise.proxmox.com/debian/proxmox-archive-keyring-trixie.gpg"
pbc_keyring_path: /usr/share/keyrings/proxmox-archive-keyring.gpg
pbc_client_apt_sources_file: /etc/apt/sources.list.d/pbs-client.sources

# Target user on the host
pbc_user: fletcher
pbc_home: "/home/{{ pbc_user }}"

# Where scripts land on the host
pbc_src_dir: "{{ pbc_home }}/git/pbc-scripts"
pbc_bin_dir: "{{ pbc_home }}/bin"

# Git source for the scripts (this repo). Use a tag for reproducibility.
pbc_repo: "https://github.com/fletcherm/pbc-scripts.git"
pbc_version: "main"

# PBS env file location
pbc_env_dir: "{{ pbc_home }}/.config/pbc-scripts"
pbc_env_file: "{{ pbc_env_dir }}/pbc.env"

# Optionally install a zsh extension to export these envs in interactive shells
pbc_install_zsh_extension: true
pbc_zsh_ext_dir: "{{ pbc_home }}/.zshrc.d"
pbc_zsh_ext_file: "{{ pbc_zsh_ext_dir }}/pbc-env.zsh"
